version: '3'

services:
  mysql:
    container_name: ship-routes-mysql
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ships; CREATE DATABASE IF NOT EXISTS ports; CREATE DATABASE IF NOT EXISTS routes; CREATE DATABASE IF NOT EXISTS backoffice;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  rabbitmq:
    container_name: ship-routes-rabbitmq
    image: 'rabbitmq:3.7-management'
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=shiproutes
      - RABBITMQ_DEFAULT_PASS=sh1pr0ut3s

  java:
    container_name: ship-routes-java
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8030:8080"
    volumes:
      - .:/app:delegated
    env_file:
      - .env
    tty: true
    depends_on:
      - mysql
      - rabbitmq
